name = "TimeStructures"
uuid = "260f4295-b40d-47c0-843b-64f3de373d90"
authors = ["Lars Hellemo <Lars.Hellemo@sintef.no> "]
version = "0.1.9"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "^1.6"
